"""empty message

Revision ID: 119ae3e2222d
Revises: 60d91e3cf3a5
Create Date: 2022-11-14 14:27:38.062376

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "119ae3e2222d"
down_revision = "60d91e3cf3a5"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
