"""empty message

Revision ID: 686d98beee3b
Revises: 119ae3e2222d
Create Date: 2022-11-15 09:12:48.627133

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '686d98beee3b'
down_revision = '119ae3e2222d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_artists_artist_name', table_name='artists')
    op.create_index(op.f('ix_artists_artist_name'), 'artists', ['artist_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_artists_artist_name'), table_name='artists')
    op.create_index('ix_artists_artist_name', 'artists', ['artist_name'], unique=False)
    # ### end Alembic commands ###
